### ISSUE TITLE
Possible issue when handling really big non-null-terminated strings (like std::string_view)

### ISSUE THREAD

**Issue by libTorrentUser** [rokudev/rostd#2]
First of all, printx is awesome! Really really awesome.

But we may have an issue here
https://github.com/rokudev/rostd/blob/e8f2be882f88c2e367caec7e3db218bb1274d354/include/rostd/printx.hpp#L127

What if the size if too big for an `int`? 

I agree that the likelihood of someone trying to print a string with more than 2 billion chars is extremely small and, in fact, before stumbling upon printx, I've been printing non null-terminated strings exactly like the library does it. There are, of course, systems where `int` is only 16 bits but, then again, those guys will probably crash and burn way before one starts trying to print 33K char strings.

The most harmless solution I could think of would be using `std::min` with `std::numeric_limits<int>::max()` to cap the value in case is too big.

I must confess though I'd rather see the code staying exactly like it is right now than to add stuff that might cause performance penalties.

Anyway, just thought I should put the issue out there. 

PS: printx is awesome!

**Comment by libTorrentUser** [comment]
Another hacky alternative would be to, somehow, replace the the `".*s"` by `".*s.*s"` and then pass the remainder of the string to that second `.*s`

And to think all this mess wouldn't be need if they just created a real specifier for non null-terminated stuff. Tsc...

**Comment by agraham-roku** [comment]
The printf spec says it's an integer, so whatever it is, it's cast to an `int`. If the caller's value is too big to fit in an `int`, that's something the caller will need to account for. Doing so in the library would be a relatively significant amount of work for very little gain.

Thanks for the suggestion!
